version: "3.8"

services:
  http-server:
    build: .
    command: >
      sh -c "poetry run python manage.py migrate &&
             poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - PYTHONPATH=/usr/src/app/src
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://postgres:1031@db:5432/event_management
      - DEBUG=1

  db:
    image: postgres:16.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: event_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1031
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

  celery:
    build: .
    command: celery -A src.config worker --loglevel=info
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - redis
      - db
    environment:
      - PYTHONPATH=/usr/src/app/src
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://postgres:1031@db:5432/event_management

  celery-beat:
    build: .
    command: celery -A src.config beat --loglevel=info
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - redis
      - db
    environment:
      - PYTHONPATH=/usr/src/app/src
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://postgres:1031@db:5432/event_management

volumes:
  postgres_data: