version: "3.8"

services:
  http-server:
    build: .
    command: >
      sh -c "poetry run python manage.py migrate &&
             poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1

  db:
    image: postgres:16.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: event_management  # Create event_management DB
      POSTGRES_USER: postgres      # Replace with your user
      POSTGRES_PASSWORD: 1031
    env_file:
      - .env

volumes:
  postgres_data: